apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-pv
  labels:
    type: azure
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: tting-easyva-fileshare
    readOnly: false


