---
apiVersion: batch/v1
kind: Job
metadata:
  name: study-creator
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-database
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          command:
          - /bin/sh
          - -c
          - -e
          - -x
          - |
            until mysqladmin ping -h mysql -u$(MYSQL_USER) -p$(MYSQL_PASSWORD);
            do echo "waiting for mysql"; sleep 2; done;
          envFrom:
            - secretRef:
                name: mysql-secrets
      containers:
        - name: study-creator
          image: idm-docker-staging.packages.idmod.org/laser/laser_calib:latest
          imagePullPolicy: Always
          command:
          - /bin/sh
          - -c
          - -e
          - -x
          - |
            optuna create-study --skip-if-exists --direction minimize \
            --study-name "${STUDY_NAME}" --storage \
            "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DB}"
          envFrom:
            - secretRef:
                name: mysql-secrets
      imagePullSecrets:
        - name: idmodregcred3

