---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "superSecretPassword"
  POSTGRES_USER: "optuna"
  POSTGRES_DB: "optunaDatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        # - name: rsvsimnfs
        #   nfs:
        #     server: 10.24.42.254
        #     path: /volume1/volume1-data/RSV/db
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: azure-managed-disk
            # claimName: rsvsim-pv-claim     # testing with a local volume on node
      tolerations:
        - key: "nodepool"
          operator: "Equal"
          value: "highcpu"
          effect: "NoSchedule"        
      containers:
        - name: postgres
          image: postgres:16.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            # - mountPath: /var/lib/postgresql/data
            #   name: rsvsimnfs
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
              subPath: postgres
              #  subPath: "rsvsim/postgres"              
          args: ["-c", "max_connections=1000", "-c", "shared_buffers=2048MB", "-c", "logging_collector=on"]
          envFrom:
            - secretRef:
                name: postgres-secrets
          ports:
            - containerPort: 5432
      nodeSelector:
        nodepool: highcpu            
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-exposed
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer
---